### ISSUE TITLE
Object.BlobList() seemingly always returns an empty dictionary

### ISSUE THREAD

**Issue by alexrp** [erikzaadi/GithubSharp#6]
For example:

var objectApi = new Object(cache, logger);
objectApi.Authenticate(...);
var blobs = objectApi.BlobList("xamarin", "monotouch-samples", "master");

Two things are worth noting here:

1) The third argument is the branch, not the SHA-1. See: http://develop.github.com/p/object.html
2) An empty dictionary is always returned.

Any help in figuring out what's going wrong here would be great.

Thanks!

**Comment by alexrp** [comment]
BTW, if you try to curl it manually, e.g.: curl http://github.com/api/v2/json/blob/all/xamarin/monotouch-samples/master, it works.

**Comment by alexrp** [comment]
From what I can gather, the issue might be what's described here: http://stackoverflow.com/questions/596271/deserialization-problem-with-datacontractjsonserializer (ObjectListContainer uses a Dictionary<string, string>.)

**Comment by alexrp** [comment]
I think using JavaScriptSerializer might be a good idea here.

**Comment by erikzaadi** [comment]
Thanks @alexrp , I'll have a look

**Comment by alexrp** [comment]
Please see pull request 7.
